### ISSUE TITLE
May 9 New Code Issues - Old Activities are no longer showing, Create an activity error

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-django#31]
When the new code was pushed:

- [x] None of the activities from the database are visible
- [x] Clicking on create an activity loads an error
/create_project/ is not found
Loads this error:
![image](https://user-images.githubusercontent.com/5350076/39876054-439648a0-5440-11e8-894d-9aa7260b35d8.png)
- [x] Clicking submit when creating an activity has no effect

From @moileretour  

Problem: all the urls in the back end were changed but the front-end URLS were not changed.
Old redirect is to : /create_project/ 
but the new address is : 
/projects/create/ 

and this is the same for all the urls... the solution is to update the Html and javascript

**Comment by moileretour** [comment]
Urls used in templates are not the same than the urls used in urls.py
