### ISSUE TITLE
Registration Error in a new Clone project setup

### ISSUE THREAD

**Issue by djsethi09** [joatuapp/joatu-django#38]
Just cloned the app and setup the requirements. Ran the migrations, and while using the sign up feature it did not work due to some api url not found. I just have started working on it, please let me know what's gone missing before i debug it.

following is the log
[15/May/2018 12:45:47] "POST /accounts/index/ HTTP/1.1" 302 0
[15/May/2018 12:45:47] "GET /accounts/index/ HTTP/1.1" 200 6622
Not Found: /api/profiles//
[15/May/2018 12:45:47] "GET /api/profiles// HTTP/1.1" 404 22275

**Comment by santoshyadav198613** [comment]
I am getting the same issue.

**Comment by joatu** [comment]
It might be that you need to integrate the google maps API. It's free (basically). You get $200/month of credit to use it.

https://cloud.google.com/maps-platform/pricing/

@moileretour Is this the issue?

**Comment by santoshyadav198613** [comment]
Completed all the steps mentioned still getting the same error.

**Comment by moileretour** [comment]
I have pushed a new commit. it should be fixed. (it was a javascript line trying to call profile api before the user has created its profile)
